### PR TITLE
Switch [directories] to [xdg] to work on Windows

### LINKED ISSUE #27: directories dependency does not work on Windows
The last version of bogue pulled in the `directories` package. The problem is that package does not work on Windows: https://github.com/OCamlPro/directories/issues/14

That's stuck because `xdg` has become the standard (its logic has made its way into the ocaml compiler for profile calculation). And the authors don't have access to a Windows machine.

Thoughts?

### PR DESCRIPTION
**Pull request by jonahbeckford**
xdg.3.4.0 was the first version to have good Windows defaults.

It should be the same configuration directory on Linux but not Windows (which was never working) and not macOS. macOS used to be $HOME/Library/Application Support/<project_path> where <project_path> was qualifier.organization.application (org.sanette.bogue).

Fixes https://github.com/sanette/bogue/issues/27

### CODE REVIEW

**Comment by jonahbeckford** [comment]
(I haven't tested on Linux, so it would be good if someone could check that existing configuration is still read on Linux)

File: lib/b_theme.ml [hunk 1]
```diff
@@ -95,21 +95,14 @@ let (//) = Filename.concat
...
-  | None -> failwith "Can't compute configuration directory path."
-  | Some config_dir -> config_dir
+let xdg = Xdg.create ~env:Sys.getenv_opt ()
+
+let home = Xdg.home_dir xdg
+
+let conf =
+  let application = "bogue" in
+  let config_dir = Xdg.config_dir xdg in
+  Filename.concat config_dir application
```
Comment (sanette) [inline lib/b_theme.ml]: `config_dir // application`

(just to be consistent with the rest)

Comment (jonahbeckford) [reply lib/b_theme.ml]: Didn't see that. Now it is changed! Thx

**Comment by sanette** [comment]
thanks!
